name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true cygnetops/react-test npm test

      - name: Set Service Key
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-404006

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: asia-south1-a

      - name: Build
        run: |-
          docker build -t sagarprasad480/multi-client:v1 -t sagarprasad480/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t sagarprasad480/multi-server:v1 -t sagarprasad480/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t sagarprasad480/multi-worker:v1 -t sagarprasad480/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push sagarprasad480/multi-client:v1
          docker push sagarprasad480/multi-server:v1
          docker push sagarprasad480/multi-worker:v1

          docker push sagarprasad480/multi-client:${{ env.SHA }}
          docker push sagarprasad480/multi-server:${{ env.SHA }}
          docker push sagarprasad480/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=sagarprasad480/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=sagarprasad480/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=sagarprasad480/multi-worker:${{ env.SHA }}
